export const videoJsPtBr: Record<string, string> = {
  Play: 'Reproduzir',
  Pause: 'Pausar',
  'Current Time': 'Tempo atual',
  Duration: 'Duração',
  'Remaining Time': 'Tempo restante',
  'Stream Type': 'Tipo de transmissão',
  LIVE: 'AO VIVO',
  Loaded: 'Carregado',
  Progress: 'Progresso',
  'Fullscreen': 'Tela cheia',
  'Non-Fullscreen': 'Sair da tela cheia',
  Mute: 'Silenciar',
  Unmute: 'Ativar áudio',
  'Playback Rate': 'Velocidade de reprodução',
  Subtitles: 'Legendas',
  Captions: 'Legendas ocultas',
  'subtitles off': 'Desativadas',
  'captions off': 'Desativadas',
  'Audio Track': 'Faixa de áudio',
  Chapters: 'Capítulos',
  Descriptions: 'Audiodescrição',
  Auto: 'Automático',
  Off: 'Desativado',
  On: 'Ativado',
  Close: 'Fechar',
  'Close Modal Dialog': 'Fechar janela',
  'Picture-in-Picture': 'Janela flutuante',
  'Exit Picture-in-Picture': 'Sair da janela flutuante',
  Replay: 'Repetir',
  'Play Video': 'Reproduzir vídeo',
  'Quality': 'Qualidade'
};
